bug fix and optimizations
hochbaumGroup/pseudoflow-parametric-cut pull request #39
Opened 2024-10-02 19:43 UTC by airribarrac

2024-12-14 20:01 UTC, quic0 commented
Hi, I took a look at the changes. I do not have a good enough memory of the code and without a description I can't validate that. I'll trust that you and the rest of the team did that. I'll add a couple of other comments on the PR. Let me know if you plan to address them. If not, I can accept the code as is as I am not actively maintaining it.

Lastly, do you have a toy instance that surface the bug identified? If yes, it would be great if you could add it to `tests/test_hpf.py`.

2024-12-14 20:14 UTC, quic0 requested changes

2024-12-14 20:14 UTC, quic0 commented on src/pseudoflow/core/libhpf.c
> +    //free(all_sink);
Please delete unnecessary commented out code. Debug help is fine (although in hindsight, https://stackoverflow.com/questions/1644868/define-macro-for-debug-printing-in-c is better)

2024-12-14 20:14 UTC, quic0 commented on src/pseudoflow/core/libhpf.c
> +      if(highOptimalSourceIndicator[i] || !lowOptimalSourceIndicator[i]){
See comment on commented out code.

2024-12-14 20:14 UTC, quic0 commented on src/pseudoflow/core/libhpf.c
> +        //free(pdifference_min_max_intersect);
See comment on commented out code.

2024-12-14 20:14 UTC, quic0 commented on src/pseudoflow/core/libhpf.c
> +//free(pdifference_low_high);
See comment on commented out code.

2024-12-14 20:14 UTC, quic0 commented on src/pseudoflow/core/libhpf.c
> +    //qsort(arcListSuper, numArcsSuper, sizeof(Arc), cmpArc);
Sort no longer needed?

2024-12-14 20:14 UTC, quic0 commented on src/pseudoflow/core/libhpf.c
> +	//free(problem->sourceSet);
Have you confirmed that no memory leaks were introduced with e.g. valgrind?
Please delete any code that is no longer needed.

2024-12-17 20:04 UTC, airribarrac commented
Hi Quico,

Thank you for your feedback. I am going to address the comments given by you.
Regarding the changes in this version, the first change is a bug fix for not missing breakponts. During the recursion, when the lambda intersection is found to be a breakpoint (i.e. there is a difference on the number of nodes in the source set for the min and max subproblems), the code did not further recurse. On some big instances, this means missing a few breakpoints. The bug fix is to recurse whether the intersection is a breakpoint or not.

The other changes done are optimizations to the performance. One change done is that when creating the subproblems of the recursion, instead of allocating and freeing memory each time a subproblem is created, to allocate memory for the biggest size of subproblem possible once, and saving that memory address for later use instead of freeing it. This reduces the number of calls to malloc, which can be costly in time, and can also help avoid memory fragmentation.

I also rewrote other parts of the code in a more cache-friendly way, which helped reduce execution time, and also reordered the order of members of struct for better memory alignment, which slightly reduces memory usage and also has a performance gain.

I'll tell you once all your comments are addressed.

2024-12-18 04:13 UTC, quic0 commented
Hi Ayleen,

Thank you for the clear explanation. That will help with the CR review.
These all sound like great enhancements. I could see the problem with
recursion on a break point occurring indeed.

Let me know once I should that another look.

Quico

On Tue, Dec 17, 2024, 12:04 Ayleen Irribarra ***@***.***>
wrote:

> Hi Quico,
>
> Thank you for your feedback. I am going to address the comments given by
> you.
> Regarding the changes in this version, the first change is a bug fix for
> not missing breakponts. During the recursion, when the lambda intersection
> is found to be a breakpoint (i.e. there is a difference on the number of
> nodes in the source set for the min and max subproblems), the code did not
> further recurse. On some big instances, this means missing a few
> breakpoints. The bug fix is to recurse whether the intersection is a
> breakpoint or not.
>
> The other changes done are optimizations to the performance. One change
> done is that when creating the subproblems of the recursion, instead of
> allocating and freeing memory each time a subproblem is created, to
> allocate memory for the biggest size of subproblem possible once, and
> saving that memory address for later use instead of freeing it. This
> reduces the number of calls to malloc, which can be costly in time, and can
> also help avoid memory fragmentation.
>
> I also rewrote other parts of the code in a more cache-friendly way, which
> helped reduce execution time, and also reordered the order of members of
> struct for better memory alignment, which slightly reduces memory usage and
> also has a performance gain.
>
> I'll tell you once all your comments are addressed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hochbaumGroup/pseudoflow-parametric-cut/pull/39#issuecomment-2549498641>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPW52SQOTMQGTQPITA5K3T2GB7WDAVCNFSM6AAAAABPILU7OGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBZGQ4TQNRUGE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-01-12 20:36 UTC, quic0 commented
Hi Ayleen, let me know once I should take another look.

2025-02-01 19:25 UTC, merged